server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/

#用于服务降级 在注解@FeignClient中添加fallbackFactory属性值
feign:
  hystrix:
    #在feign开启hystrix
    enabled: true