server:
  port: 80

eureka:
  client:
    #表示不向注册中心注册自己
    register-with-eureka: true
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  #配置actuator图形化界面
  instance:
    #让其不直接显示ip地址
    instance-id: order80
    #可以鼠标悬浮式查看ip地址
    prefer-ip-address: true
spring:
  application:
    name: cloud-order-service